package org.godotengine.godotxrtoolsdemo;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int fragment_fast_out_extra_slow_in = 0x7f010000;
    }

    public static final class animator {
        public static final int fragment_close_enter = 0x7f020000;
        public static final int fragment_close_exit = 0x7f020001;
        public static final int fragment_fade_enter = 0x7f020002;
        public static final int fragment_fade_exit = 0x7f020003;
        public static final int fragment_open_enter = 0x7f020004;
        public static final int fragment_open_exit = 0x7f020005;
    }

    public static final class attr {
        public static final int alpha = 0x7f030000;
        public static final int font = 0x7f030001;
        public static final int fontProviderAuthority = 0x7f030002;
        public static final int fontProviderCerts = 0x7f030003;
        public static final int fontProviderFetchStrategy = 0x7f030004;
        public static final int fontProviderFetchTimeout = 0x7f030005;
        public static final int fontProviderPackage = 0x7f030006;
        public static final int fontProviderQuery = 0x7f030007;
        public static final int fontStyle = 0x7f030008;
        public static final int fontVariationSettings = 0x7f030009;
        public static final int fontWeight = 0x7f03000a;
        public static final int ttcIndex = 0x7f03000b;
    }

    public static final class color {
        public static final int notification_action_color_filter = 0x7f040000;
        public static final int notification_icon_bg_color = 0x7f040001;
        public static final int ripple_material_light = 0x7f040002;
        public static final int secondary_text_default_material_light = 0x7f040003;
    }

    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f050000;
        public static final int compat_button_inset_vertical_material = 0x7f050001;
        public static final int compat_button_padding_horizontal_material = 0x7f050002;
        public static final int compat_button_padding_vertical_material = 0x7f050003;
        public static final int compat_control_corner_material = 0x7f050004;
        public static final int compat_notification_large_icon_max_height = 0x7f050005;
        public static final int compat_notification_large_icon_max_width = 0x7f050006;
        public static final int notification_action_icon_size = 0x7f050007;
        public static final int notification_action_text_size = 0x7f050008;
        public static final int notification_big_circle_margin = 0x7f050009;
        public static final int notification_content_margin_start = 0x7f05000a;
        public static final int notification_large_icon_height = 0x7f05000b;
        public static final int notification_large_icon_width = 0x7f05000c;
        public static final int notification_main_column_padding_top = 0x7f05000d;
        public static final int notification_media_narrow_margin = 0x7f05000e;
        public static final int notification_right_icon_size = 0x7f05000f;
        public static final int notification_right_side_padding_top = 0x7f050010;
        public static final int notification_small_icon_background_padding = 0x7f050011;
        public static final int notification_small_icon_size_as_large = 0x7f050012;
        public static final int notification_subtext_size = 0x7f050013;
        public static final int notification_top_pad = 0x7f050014;
        public static final int notification_top_pad_large_text = 0x7f050015;
        public static final int text_edit_height = 0x7f050016;
    }

    public static final class drawable {
        public static final int notification_action_background = 0x7f060000;
        public static final int notification_bg = 0x7f060001;
        public static final int notification_bg_low = 0x7f060002;
        public static final int notification_bg_low_normal = 0x7f060003;
        public static final int notification_bg_low_pressed = 0x7f060004;
        public static final int notification_bg_normal = 0x7f060005;
        public static final int notification_bg_normal_pressed = 0x7f060006;
        public static final int notification_icon_background = 0x7f060007;
        public static final int notification_template_icon_bg = 0x7f060008;
        public static final int notification_template_icon_low_bg = 0x7f060009;
        public static final int notification_tile_bg = 0x7f06000a;
        public static final int notify_panel_notification_icon_bg = 0x7f06000b;
        public static final int splash = 0x7f06000c;
        public static final int splash_bg_color = 0x7f06000d;
        public static final int splash_drawable = 0x7f06000e;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f070000;
        public static final int accessibility_custom_action_0 = 0x7f070001;
        public static final int accessibility_custom_action_1 = 0x7f070002;
        public static final int accessibility_custom_action_10 = 0x7f070003;
        public static final int accessibility_custom_action_11 = 0x7f070004;
        public static final int accessibility_custom_action_12 = 0x7f070005;
        public static final int accessibility_custom_action_13 = 0x7f070006;
        public static final int accessibility_custom_action_14 = 0x7f070007;
        public static final int accessibility_custom_action_15 = 0x7f070008;
        public static final int accessibility_custom_action_16 = 0x7f070009;
        public static final int accessibility_custom_action_17 = 0x7f07000a;
        public static final int accessibility_custom_action_18 = 0x7f07000b;
        public static final int accessibility_custom_action_19 = 0x7f07000c;
        public static final int accessibility_custom_action_2 = 0x7f07000d;
        public static final int accessibility_custom_action_20 = 0x7f07000e;
        public static final int accessibility_custom_action_21 = 0x7f07000f;
        public static final int accessibility_custom_action_22 = 0x7f070010;
        public static final int accessibility_custom_action_23 = 0x7f070011;
        public static final int accessibility_custom_action_24 = 0x7f070012;
        public static final int accessibility_custom_action_25 = 0x7f070013;
        public static final int accessibility_custom_action_26 = 0x7f070014;
        public static final int accessibility_custom_action_27 = 0x7f070015;
        public static final int accessibility_custom_action_28 = 0x7f070016;
        public static final int accessibility_custom_action_29 = 0x7f070017;
        public static final int accessibility_custom_action_3 = 0x7f070018;
        public static final int accessibility_custom_action_30 = 0x7f070019;
        public static final int accessibility_custom_action_31 = 0x7f07001a;
        public static final int accessibility_custom_action_4 = 0x7f07001b;
        public static final int accessibility_custom_action_5 = 0x7f07001c;
        public static final int accessibility_custom_action_6 = 0x7f07001d;
        public static final int accessibility_custom_action_7 = 0x7f07001e;
        public static final int accessibility_custom_action_8 = 0x7f07001f;
        public static final int accessibility_custom_action_9 = 0x7f070020;
        public static final int action_container = 0x7f070021;
        public static final int action_divider = 0x7f070022;
        public static final int action_image = 0x7f070023;
        public static final int action_text = 0x7f070024;
        public static final int actions = 0x7f070025;
        public static final int appIcon = 0x7f070026;
        public static final int approveCellular = 0x7f070027;
        public static final int async = 0x7f070028;
        public static final int blocking = 0x7f070029;
        public static final int buttonRow = 0x7f07002a;
        public static final int cancelButton = 0x7f07002b;
        public static final int chronometer = 0x7f07002c;
        public static final int description = 0x7f07002d;
        public static final int dialog_button = 0x7f07002e;
        public static final int downloadButton = 0x7f07002f;
        public static final int downloaderDashboard = 0x7f070030;
        public static final int forever = 0x7f070031;
        public static final int fragment_container_view_tag = 0x7f070032;
        public static final int godot_fragment_container = 0x7f070033;
        public static final int icon = 0x7f070034;
        public static final int icon_group = 0x7f070035;
        public static final int info = 0x7f070036;
        public static final int italic = 0x7f070037;
        public static final int line1 = 0x7f070038;
        public static final int line3 = 0x7f070039;
        public static final int normal = 0x7f07003a;
        public static final int notificationLayout = 0x7f07003b;
        public static final int notification_background = 0x7f07003c;
        public static final int notification_main_column = 0x7f07003d;
        public static final int notification_main_column_container = 0x7f07003e;
        public static final int pauseButton = 0x7f07003f;
        public static final int progressAsFraction = 0x7f070040;
        public static final int progressAsPercentage = 0x7f070041;
        public static final int progressAverageSpeed = 0x7f070042;
        public static final int progressBar = 0x7f070043;
        public static final int progressTimeRemaining = 0x7f070044;
        public static final int progress_bar = 0x7f070045;
        public static final int progress_bar_frame = 0x7f070046;
        public static final int progress_text = 0x7f070047;
        public static final int resumeOverCellular = 0x7f070048;
        public static final int right_icon = 0x7f070049;
        public static final int right_side = 0x7f07004a;
        public static final int special_effects_controller_view_tag = 0x7f07004b;
        public static final int statusText = 0x7f07004c;
        public static final int tag_accessibility_actions = 0x7f07004d;
        public static final int tag_accessibility_clickable_spans = 0x7f07004e;
        public static final int tag_accessibility_heading = 0x7f07004f;
        public static final int tag_accessibility_pane_title = 0x7f070050;
        public static final int tag_screen_reader_focusable = 0x7f070051;
        public static final int tag_transition_group = 0x7f070052;
        public static final int tag_unhandled_key_event_manager = 0x7f070053;
        public static final int tag_unhandled_key_listeners = 0x7f070054;
        public static final int text = 0x7f070055;
        public static final int text2 = 0x7f070056;
        public static final int textPausedParagraph1 = 0x7f070057;
        public static final int textPausedParagraph2 = 0x7f070058;
        public static final int time = 0x7f070059;
        public static final int time_remaining = 0x7f07005a;
        public static final int title = 0x7f07005b;
        public static final int view_tree_lifecycle_owner = 0x7f07005c;
        public static final int view_tree_saved_state_registry_owner = 0x7f07005d;
        public static final int view_tree_view_model_store_owner = 0x7f07005e;
        public static final int visible_removing_fragment_view_tag = 0x7f07005f;
        public static final int wifiSettingsButton = 0x7f070060;
    }

    public static final class integer {
        public static final int status_bar_notification_info_maxnum = 0x7f080000;
    }

    public static final class layout {
        public static final int custom_dialog = 0x7f090000;
        public static final int downloading_expansion = 0x7f090001;
        public static final int godot_app_layout = 0x7f090002;
        public static final int notification_action = 0x7f090003;
        public static final int notification_action_tombstone = 0x7f090004;
        public static final int notification_template_custom_big = 0x7f090005;
        public static final int notification_template_icon_group = 0x7f090006;
        public static final int notification_template_part_chronometer = 0x7f090007;
        public static final int notification_template_part_time = 0x7f090008;
        public static final int status_bar_ongoing_event_progress_bar = 0x7f090009;
    }

    public static final class mipmap {
        public static final int icon = 0x7f0a0000;
        public static final int icon_background = 0x7f0a0001;
        public static final int icon_foreground = 0x7f0a0002;
    }

    public static final class string {
        public static final int error_engine_setup_message = 0x7f0b0000;
        public static final int error_missing_vulkan_requirements_message = 0x7f0b0001;
        public static final int godot_project_name_string = 0x7f0b0002;
        public static final int kilobytes_per_second = 0x7f0b0003;
        public static final int notification_download_complete = 0x7f0b0004;
        public static final int notification_download_failed = 0x7f0b0005;
        public static final int state_completed = 0x7f0b0006;
        public static final int state_connecting = 0x7f0b0007;
        public static final int state_downloading = 0x7f0b0008;
        public static final int state_failed = 0x7f0b0009;
        public static final int state_failed_cancelled = 0x7f0b000a;
        public static final int state_failed_fetching_url = 0x7f0b000b;
        public static final int state_failed_sdcard_full = 0x7f0b000c;
        public static final int state_failed_unlicensed = 0x7f0b000d;
        public static final int state_fetching_url = 0x7f0b000e;
        public static final int state_idle = 0x7f0b000f;
        public static final int state_paused_by_request = 0x7f0b0010;
        public static final int state_paused_network_setup_failure = 0x7f0b0011;
        public static final int state_paused_network_unavailable = 0x7f0b0012;
        public static final int state_paused_roaming = 0x7f0b0013;
        public static final int state_paused_sdcard_unavailable = 0x7f0b0014;
        public static final int state_paused_wifi_disabled = 0x7f0b0015;
        public static final int state_paused_wifi_unavailable = 0x7f0b0016;
        public static final int state_unknown = 0x7f0b0017;
        public static final int status_bar_notification_info_overflow = 0x7f0b0018;
        public static final int text_button_cancel = 0x7f0b0019;
        public static final int text_button_cancel_verify = 0x7f0b001a;
        public static final int text_button_pause = 0x7f0b001b;
        public static final int text_button_resume = 0x7f0b001c;
        public static final int text_button_resume_cellular = 0x7f0b001d;
        public static final int text_button_wifi_settings = 0x7f0b001e;
        public static final int text_error_title = 0x7f0b001f;
        public static final int text_paused_cellular = 0x7f0b0020;
        public static final int text_paused_cellular_2 = 0x7f0b0021;
        public static final int text_validation_complete = 0x7f0b0022;
        public static final int text_validation_failed = 0x7f0b0023;
        public static final int text_verifying_download = 0x7f0b0024;
        public static final int time_remaining = 0x7f0b0025;
        public static final int time_remaining_notification = 0x7f0b0026;
    }

    public static final class style {
        public static final int ButtonBackground = 0x7f0c0000;
        public static final int GodotAppMainTheme = 0x7f0c0001;
        public static final int GodotAppSplashTheme = 0x7f0c0002;
        public static final int NotificationText = 0x7f0c0003;
        public static final int NotificationTextShadow = 0x7f0c0004;
        public static final int NotificationTitle = 0x7f0c0005;
        public static final int TextAppearance_Compat_Notification = 0x7f0c0006;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0c0007;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0c0008;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0c0009;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0c000a;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0c000b;
        public static final int Widget_Compat_NotificationActionText = 0x7f0c000c;
    }

    public static final class xml {
        public static final int godot_provider_paths = 0x7f0e0000;
    }
}